### ISSUE TITLE
conda python not found in evalSAD.sh

### ISSUE THREAD

**Issue by sliaqat1** [aclew/DiViMe#11]
When running the evalSAD.sh script, python in the path "/home/vagrant/anaconda/bin/python" wasn't being found. As a result, the output for the evaluations all had similar values of either 0, 25, 75, or 100%. After tinkering around in the virtual machine, I noticed that python had appeared in the directory, but I'm not sure what caused it. 
I followed the instruction in the readme. The test script ran without problems and gave my the "everything is OK!" message. My data folder has a set of audio files in wav format and a set of corresponding labels as rttm files with the same basename as the wav files.

**Comment by riebling** [comment]
I believe this is also close-able based on fixes in the SRVK DiViMe that ensure anaconda is installed, and python is on the default PATH of the default 'vagrant' VM user.
The test script has changed greatly since then, and had been giving false "everything is OK" at the time of this report - and has likewise been corrected
