### ISSUE TITLE
error running diartk.sh

### ISSUE THREAD

**Issue by jihopark** [aclew/DiViMe#9]
Hi, `test.sh` was successful and `vagrant ssh -c "tools/noisemes_sad.sh data/"` also produces results.

However, when I try to run diartk.sh with `vagrant ssh -c "tools/diartk.sh data/ noisemes"`

I get:

```wavs and transcriptions found !
Tests finished
treating guy_girl_waiter_16k
tools/diartk.sh: line 122: HCopy: command not found
Could not open feature file for reading </vagrant/data//temp_diartk/guy_girl_waiter_16k.fea>
cp: cannot stat '/vagrant/data//temp_diartk/guy_girl_waiter_16k.rttm': No such file or directory
treating homebank1
tools/diartk.sh: line 122: HCopy: command not found
Could not open feature file for reading </vagrant/data//temp_diartk/homebank1.fea>
cp: cannot stat '/vagrant/data//temp_diartk/homebank1.rttm': No such file or directory
Connection to 127.0.0.1 closed.
```

`guy_girl_waiter_16k.wav` & `homebank1.wav` are two files I would like to test inside `data/`

**Comment by riebling** [comment]
if the HCopy command is not found, that's a sign that HTK was not installed. When setting up, did you obtain a copy of the stable HTK binary and place it in the working directory, and rename it to HTK.tar.gz?

(from README)
    Install HTK

HTK is used by some of these tools (until we find and implement an open-source replacement). We are not allowed to distribute HTK, so unfortunately you have to get it yourself.

  1    Go to the HTK download page http://htk.eng.cam.ac.uk/download.shtml
  2  Register by following the instructions on the left (under "Getting HTK": Register)
  3 Check that you have received your password via email; you will need it for the next step.
  4 Find the link that reads "HTK source code" under your system (if you have a mac, it will be under "Linux/unix downloads"). Notice that you will need your username and password (from the previous step). The download is probably called HTK-3.4.1.tar.gz, although the numbers may change if they update their code.
  5 Move the HTK-*.tar.gz file into the root folder of this repository (alongside Vagrantfile), and rename it HTK.tar.gz

I see this issue is posted in the ACLEW DiViMe, which may not be the most up-to-date, as opposed to the development version SRVK DiViMe http://github.com/srvk/DiViMe

**Comment by jihopark** [comment]
Hi @riebling thanks for your fast reply.
<img width="950" alt="screen shot 2018-10-12 at 9 28 41 am" src="https://user-images.githubusercontent.com/344497/46842642-4902a780-ce01-11e8-96d6-a802047c51de.png">

As you can see I put HTK.tar.gz in DiViMe folder. Do I need to do anything extra?

also, i used the stable version of DiViMe just in case the dev version has some problem. Do you recommend the dev version instead?

**Comment by jihopark** [comment]
Hi I realized that I used the wrong HTK version (3.5beta) when I should have used 3.4 

Thanks for your help anyways!

**Comment by riebling** [comment]
OH yes! Sadly the Beta version does not build in the VM (it wants to have a graphical user interface, for one thing)
